# Site settings
title: CNVS
email: john.ashenden@mesosphere.io
description: "CNVS (pronounced 'Canvas') is a system of user interface elements and components for use across Mesosphere sites and products. CNVS defines stylistic guidelines for the design and structure of digital interfaces in an effort to ensure consistency in brand and interaction."
baseurl: "/cnvs"
twitter_username: jekyllrb
github_username:  jekyll


# Build settings
markdown: kramdown
exclude: ["styles", "images", "fonts", "javascripts"]
keep_files: ["styles", "images", "fonts", "javascripts"]
plugins:
  - jekyll-redirect-from
  - jekyll-toc
whitelist:
  - jekyll-redirect-from
kramdown:
  input: GFM
  syntax_highlighter: rouge
toc:
  max_level: 2
