# Site settings
title: CNVS
email: john.ashenden@mesosphere.io
description: "CNVS (pronounced 'Canvas') is a system of user interface elements and components for use across Mesosphere sites and products. CNVS defines stylistic guidelines for the design and structure of digital interfaces in an effort to ensure consistency in brand and interaction."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:3000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll


# Build settings
plugins:
- jekyll-redirect-from
- jekyll-toc
whitelist:
- jekyll-redirect-from
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude: ["_assets", "Gemfile", "Gemfile.lock"]
keep_files: ["assets"]
collections:
  pages:
    output: true
    permalink: /:path
toc:
  max_level: 2
